iingyeo/iingyeo

build.gradle

[#20] apply spring boot 1.3.0.M1

[#20] apply spring boot 1.3.0.M1

---

build.gradle
src/main/java/iingyeo/entity/User.java
src/main/java/iingyeo/repository/UserRepository.java

#24 apply querydsl-mongodb

---

build.gradle
src/main/java/iingyeo/controller/UserController.java

- fixed typo

---

src/main/java/iingyeo/controller/UserController.java
src/main/java/iingyeo/service/UserService.java
src/main/java/iingyeo/service/impl/UserServiceImpl.java
src/test/java/iingyeo/service/UserServiceTest.java

to close "service layer 추가 #27" issue

added service layer

---

build.gradle
src/main/java/iingyeo/IingyeoApplication.java
src/main/java/iingyeo/config/OAuth2Config.java
src/main/java/iingyeo/controller/UserController.java
src/main/resources/application.properties

#29 apply oauth2 security for rest api

#29 apply oauth2 security for rest api

---

src/main/java/iingyeo/config/OAuth2Config.java
src/main/java/iingyeo/config/WebSecurityConfig.java
src/main/java/iingyeo/entity/User.java
src/main/java/iingyeo/model/UserRequest.java
src/main/java/iingyeo/model/UserResponse.java
src/main/java/iingyeo/repository/UserRepository.java
src/main/java/iingyeo/service/impl/CustomUserDetailsServiceImpl.java
src/main/java/iingyeo/service/impl/UserServiceImpl.java
src/test/java/iingyeo/controller/UserControllerTest.java
src/test/java/iingyeo/repository/UserRepositoryTest.java
src/test/java/iingyeo/service/UserServiceTest.java

implemented mongodb authentication

implemented mongodb authentication

---

src/test/java/iingyeo/controller/UserControllerTest.java

#33 implemented controller unit test using access token

#33 implemented controller unit test using access token

---

src/main/resources/static/index.html
src/main/resources/static/js/JSXTransformer.js
src/main/resources/static/js/react-bootstrap.js
src/main/resources/static/js/react.js

added react, react-bootstrap

---

src/main/resources/static/index.html

- implemented login request

---

build.gradle
src/main/java/iingyeo/controller/AuthenticationController.java
src/test/java/iingyeo/controller/AbstractControllerTest.java
src/test/java/iingyeo/controller/AuthenticationControllerTest.java
src/test/java/iingyeo/controller/UserControllerTest.java

- implemented authentication contoller

- implemented authentication contoller

---

src/main/java/iingyeo/controller/AuthenticationController.java
src/main/java/iingyeo/filter/SimpleCORSFilter.java

- implemented logout api

---

src/main/java/iingyeo/controller/AuthenticationController.java
src/main/java/iingyeo/model/IingyeoUserDetails.java
src/main/java/iingyeo/service/impl/CustomUserDetailsServiceImpl.java

- #43 refactoring get logged in user api

- #43 refactoring get logged in user api

---

.gitignore
src/main/java/iingyeo/controller/CardController.java
src/main/java/iingyeo/service/CardService.java
src/main/java/iingyeo/service/impl/CardServiceImpl.java
src/test/java/iingyeo/controller/CardControllerTest.java
src/test/java/iingyeo/service/CardServiceTest.java

Card Put/Delete API 및 Test 구현 #45

add card put,delete api & test cases

---

build.gradle

- #50 update spring boot library to 1.3.0.M3

- #50 update spring boot library to 1.3.0.M3

---

build.gradle
src/main/resources/application-local.properties
src/main/resources/application.properties
src/test/java/iingyeo/IingyeoTestApplication.java
src/test/java/iingyeo/controller/AuthenticationControllerTest.java

- #52 bug fix for mongodb unit test

- #52 bug fix for mongodb unit test

---

src/main/java/iingyeo/controller/CardController.java
src/main/java/iingyeo/entity/Card.java
src/main/java/iingyeo/model/CardResponse.java
src/main/java/iingyeo/service/CardService.java
src/main/java/iingyeo/service/impl/CardServiceImpl.java
src/test/java/iingyeo/controller/CardControllerTest.java

- #13 implement like card api

---

src/main/java/iingyeo/filter/SimpleCORSFilter.java
src/main/java/iingyeo/model/CardResponse.java

- #56 set initial value for reply, like count

- #56 set initial value for reply, like count

---

build.gradle
src/main/java/iingyeo/controller/CardController.java
src/main/java/iingyeo/repository/predicate/CardPredicate.java
src/main/java/iingyeo/service/CardService.java
src/main/java/iingyeo/service/impl/CardServiceImpl.java
src/test/java/iingyeo/controller/CardControllerTest.java

- #14 implement like card list api

- #14 implement like card list api

---

src/main/java/iingyeo/controller/TagController.java
src/main/java/iingyeo/model/TagListResponse.java
src/main/java/iingyeo/model/TagResponse.java
src/main/java/iingyeo/service/TagService.java
src/main/java/iingyeo/service/impl/CardServiceImpl.java
src/main/java/iingyeo/service/impl/TagServiceImpl.java

- #9 implement tag list api

---

src/main/java/iingyeo/controller/CardController.java
src/main/java/iingyeo/repository/predicate/CardPredicate.java
src/main/java/iingyeo/service/CardService.java
src/main/java/iingyeo/service/impl/CardServiceImpl.java
src/test/java/iingyeo/controller/CardControllerTest.java
src/test/java/iingyeo/controller/TagControllerTest.java

- #8 implement child card list api

- #8 implement child card list api

---

src/main/java/iingyeo/controller/CardController.java
src/main/java/iingyeo/repository/predicate/CardPredicate.java
src/main/java/iingyeo/service/CardService.java
src/main/java/iingyeo/service/impl/CardServiceImpl.java
src/test/java/iingyeo/controller/CardControllerTest.java

- #8 implement card list by tag api

- #8 implement card list by tag api
